#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurent to run build-types after ESLint in lint-staged
npx lint-staged --concurrent false
npm run lint && npm run cache-posts && npm run compress-images && git add public
